apiVersion: v1
kind: Service
metadata:
  name: database-salvador
spec:
  selector:
    app: database
  ports:
    - protocol: TCP
      port: 27017    # Port du service DB (ex. MySQL)
      targetPort: 27017  # Port du conteneur DB
  type: ClusterIP  # Service interne uniquement

---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-salvador
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database-salvador
  template:
    metadata:
      labels:
        app: database-salvador
    spec:
      containers:
      - name: database-salvador
        image: 192.168.2.202:5000/database-mongo-salvador:1.0.0
        ports:
          - containerPort: 27017
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: "Salvador"
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: "Salvador333"
        volumeMounts:
          - name: mongo-storage
            mountPath: /data/db
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: mongo-pvc