apiVersion: v1
kind: Service
metadata:
  name: database-salvador
spec:
  selector:
    app: database-salvador
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP

---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-salvador
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database-salvador
  template:
    metadata:
      labels:
        app: database-salvador
    spec:
      containers:
      - name: database-salvador
        image: 192.168.2.202:5000/database-mongo-salvador:1.0.0
        ports:
          - containerPort: 27017
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongo-credentials
                key: root-username
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-credentials
                key: root-password
        volumeMounts:
          - name: mongo-storage
            mountPath: /data/db
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: mongo-pvc