apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  storageClassName: storage-mongo
  nfs:
    server: "192.168.2.202"
    path: "/mnt/mongo-salvador"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
  storageClassName: storage-mongo

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: oauth-htpasswd-pv
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  storageClassName: storage-oauth
  nfs:
    server: "192.168.2.202"
    path: "/mnt/chat_app_oauth"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oauth-htpasswd-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
  storageClassName: storage-oauth